Replaced global vector with passed by refference local one and deleted redundancies in the code
marcosmarp/signIn-signUp pull request #18
Opened 2021-08-16 00:05 UTC by marcosmarp

Hey, i think i enhanced the code pretty much, but there's a thing.
I tried to implement the `const` type of reference that we talked about with the `LogIn` function but I faced a problem:
Iterators don't work with `const` type of argument cause, according to what i read, they should have the hability of modifying the vector so you can't make them read only. I look up for an aswer and read a little about `const_iterators` but i wanted your opinion before implementing them.

Beside that, in every subprocess like checking if the email is already registered or the username, i used a `const` argument, the only one with troubles was the `FindUserByName` since it returns an iterator. Thanks!

2021-08-17 02:32 UTC, nahueespinosa requested changes
Left some comments!

2021-08-17 02:32 UTC, nahueespinosa commented on main.cpp
> +  getline(std::cin, new_user_temporal.email);
An e-mail is not supposed to have spaces, no need to use `getline()`.
I'd use `std::cin >> new_user_temporal.email;`

2021-08-17 02:32 UTC, nahueespinosa commented on main.cpp
> +      case SecurityQuestionOptions::kPetName ... SecurityQuestionOptions::kMothersName:
Fancy! Sadly is a non-standard [gcc extension](https://gcc.gnu.org/onlinedocs/gcc-4.1.2/gcc/Case-Ranges.html).

2021-08-17 02:32 UTC, nahueespinosa commented on main.cpp
> +std::vector<UserData>::iterator FindUserByName(const std::string& name, std::vector<UserData>& data_base) {
Yeah, returning a `const_iterator` should let you keep const-correctness.
So, try with [cbegin](https://en.cppreference.com/w/cpp/container/vector/begin) instead of `begin`.

2021-08-17 02:32 UTC, nahueespinosa commented on main.cpp
> +/*void ReplaceExistingPassword(UserData& user) { // This function overwrites an old password with a new one
Why is this commented out?

2021-08-17 02:32 UTC, nahueespinosa commented on main.cpp
> +bool CheckIfEmailAlreadyRegistered (std::string email, const std::vector<UserData>& data_base) { // This functions verifies that there are no matches between the to-be-registered email and the databa
`email` should also be a const reference here.

2021-08-17 02:32 UTC, nahueespinosa commented on main.cpp
> +bool CheckIfUsernameAlreadyRegistered (std::string entered_username, const std::vector<UserData>& data_base) { // This functions verifies that there are no matches between the to-be-registered userna
`entered_username` should also be a const reference here.

2021-08-17 02:32 UTC, nahueespinosa commented on main.cpp
> +  if (CheckIfUsernameAlreadyRegistered(new_user_temporal.name, registered_users_data) == true) {
You can omit `==  true`.

2021-08-17 02:32 UTC, nahueespinosa commented on main.cpp
>  void EnterPassword(UserData& user) {
This can be `const`, right?

2021-08-17 02:32 UTC, nahueespinosa commented on main.cpp
> +  for(auto i = 0 ; i < numberOfTabs ; i++) {
Avoid using `auto` replacing built-in types.

2021-08-17 02:58 UTC, marcosmarp commented
Implemented the corrections!

2021-08-17 03:02 UTC, marcosmarp commented on main.cpp
> +/*void ReplaceExistingPassword(UserData& user) { // This function overwrites an old password with a new one
Regarding this, those two functions were about recovering a "forgotten" password, but, since they're summoned in the LogIn process and we're trying to keep the LogIn function variables `const`, this was getting in the way, since the function is supposed to replace an existing password. I was thinking about maybe returning a bool in the LogIn process and replace the password directly in main. What do you think we should do?

2021-08-18 14:14 UTC, nahueespinosa commented on main.cpp
> +/*void ReplaceExistingPassword(UserData& user) { // This function overwrites an old password with a new one
Returning a boolean sounds good. I don't think you should replace the password in main though. You'll probably need to implement something different for changing the password.

2021-08-18 15:33 UTC, marcosmarp commented on main.cpp
> +/*void ReplaceExistingPassword(UserData& user) { // This function overwrites an old password with a new one
Okay! Should I change it know or in another branch?

2021-08-18 18:47 UTC, nahueespinosa approved these changes
Approved! I would focus on the Menu class next.

2021-08-18 18:47 UTC, nahueespinosa commented on main.cpp
> +/*void ReplaceExistingPassword(UserData& user) { // This function overwrites an old password with a new one
Another branch sounds good.

2021-08-18 19:08 UTC, merged