Add functions pointer to the Menu class
marcosmarp/signIn-signUp pull request #22
Opened 2021-08-29 23:28 UTC by marcosmarp

Solves #20 

Hey, I managed to assign functions to the menu items directly and then call those functions.

There's something that I wonder if it can be done a better way: in the Struct declaring the members of each Item in the Menu class (name, call code, assigned function) I have to specify the return type of the function that will go in the Item and also the argument type; this kinda breaks the "global" usability of the Menu class and forces me to only assign a particular return/argument type function to the Items (or change the function pointer arguments direcly on the code of the class but that isn't really practical).

Is there a way to leave the return and arguments type of the `std::function` "blank" (sort of speak) so I can assign whatever kind of function I want in it?

Thanks!

2021-08-29 23:57 UTC, nahueespinosa requested changes
Left some comments.

> Is there a way to leave the return and arguments type of the std::function "blank" (sort of speak) so I can assign whatever kind of function I want in it?

There is always a way haha. Why would you want to return something though?

2021-08-29 23:57 UTC, nahueespinosa commented on main.h
> +    std::function<void(std::vector<UserData>&)> assigned_function;
In my opinion it would be better for the function to not receive parameters. That way you can have more generic functions and solve the necessary context with a lambda. See next comments.

2021-08-29 23:57 UTC, nahueespinosa commented on main.h
> +  bool CallAssignedFunction(const int& call_code, std::vector<UserData>& function_parameter) {
You won't require a `function_parameter`.

2021-08-29 23:57 UTC, nahueespinosa commented on main.h
>    std::vector<Item> items;
I suggest you take a look at `unordered_map`. For instance, you could have `int` as keys and `Item` as values. That way you won't have to look up manually everytime you need an item.

2021-08-29 23:57 UTC, nahueespinosa commented on main.cpp
> +  main_menu.AddItem("Register", 1, RegisterNewUser);
If your class accepts `void f()` functions, you should be able to write something like this:

```cpp
main_menu.AddItem("Register", 1, [&](){ RegisterNewUser(registered_users_data); });
```

You would be creating an unnamed function object capable of capturing variables in scope.

2021-08-29 23:57 UTC, nahueespinosa commented on main.cpp
> +  main_menu.AddItem("Register", 1, RegisterNewUser);
Try to investigate about good practices with lambdas. There are some things you should be aware of before using them everywhere 😉.

2021-08-30 19:10 UTC, marcosmarp commented
Hey, managed to do everything. A couple of things:
- I used a `map` instead of `unordered_map` because in the `PrintItems` function the items were printed in a random order
- I had to add an empty (`Item() = default`) constructor to the `Item` class, otherwise the `items_map.insert` didn't work.
Tell me what you think!

2021-08-30 20:42 UTC, nahueespinosa requested changes
Nice!

> I used a map instead of unordered_map

Makes sense haha.

> I had to add an empty (Item() = default) constructor 

Not so sure about this, can you share the error?

2021-08-30 20:42 UTC, nahueespinosa commented on main.h
> +    items_map.insert({call_code, item_temp});
Why don't you use [emplace](https://en.cppreference.com/w/cpp/container/map/emplace)?

2021-08-30 20:42 UTC, nahueespinosa commented on main.h
> +    items_map.insert({call_code, item_temp});
Same here.

2021-08-30 20:42 UTC, nahueespinosa commented on main.h
> +    }
No need to have two different constructors. You can assign a [default argument](https://en.cppreference.com/w/cpp/language/default_arguments).

2021-08-30 20:42 UTC, nahueespinosa commented on main.h
> +    }
Don't forget to use const reference when passing `std::string`.

2021-08-30 20:42 UTC, nahueespinosa commented on main.h
> +    items_map[call_code].assigned_function();
What happens if there is no function assigned and the user tries to call it?

2021-08-30 20:42 UTC, nahueespinosa commented on main.h
> +    else return false;
```suggestion
    return items_map.find(input) != items_map.end();
```

2021-08-30 20:56 UTC, marcosmarp commented
It was a big bunch of code in the terminal coming from the map library and after all of that there was a "candidate expects 1 argument 0 provided" and "candidate expects 2 arguments 0 provided" pointing at the constructors of the Item class

2021-08-30 21:08 UTC, nahueespinosa commented
> It was a big bunch of code

Yeah, that's not very helpful, can you share the compiler output?
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/out-file?view=powershell-7.1

Maybe VSCode will let you save the output, idk.

2021-08-30 21:13 UTC, marcosmarp commented
Sorry, this was the compiler output:

PS C:\Users\user\Desktop\Marcos\signIn-signUp> g++ "c:\Users\user\Desktop\Marcos\signIn-signUp\main.cpp" -o main.exe ; if ($?) { start main.exe }
In file included from c:\mingw\lib\gcc\mingw32\6.3.0\include\c++\functional:55:0,
                 from c:\Users\user\Desktop\Marcos\signIn-signUp\main.h:6,
                 from c:\Users\user\Desktop\Marcos\signIn-signUp\main.cpp:1:
c:\mingw\lib\gcc\mingw32\6.3.0\include\c++\tuple: In instantiation of 'std::pair<_T1, _T2>::pair(std::tuple<_Args1 ...>&, std::tuple<_Args2 ...>&, std::_Index_tuple<_Indexes1 ...>, std::_Index_tuple<_Indexes2 ...>) [with _Args1 = {const int&}; unsigned int ..._Indexes1 = {0u}; 
_Args2 = {}; unsigned int ..._Indexes2 = {}; _T1 = const int; _T2 = Item]':
c:\mingw\lib\gcc\mingw32\6.3.0\include\c++\tuple:1575:63:   required from 'std::pair<_T1, _T2>::pair(std::piecewise_construct_t, std::tuple<_Args1 ...>, std::tuple<_Args2 ...>) [with _Args1 = {const int&}; _Args2 = {}; _T1 = const int; _T2 = Item]'
c:\mingw\lib\gcc\mingw32\6.3.0\include\c++\ext\new_allocator.h:120:4:   required from 'void __gnu_cxx::new_allocator<_Tp>::construct(_Up*, 
_Args&& ...) [with _Up = std::pair<const int, Item>; _Args = {const std::piecewise_construct_t&, std::tuple<const int&>, std::tuple<>}; _Tp = std::_Rb_tree_node<std::pair<const int, Item> >]'
c:\mingw\lib\gcc\mingw32\6.3.0\include\c++\bits\alloc_traits.h:455:4:   required from 'static void std::allocator_traits<std::allocator<_CharT> >::construct(std::allocator_traits<std::allocator<_CharT> >::allocator_type&, _Up*, _Args&& ...) [with _Up = std::pair<const int, Item>; _Args = {const std::piecewise_construct_t&, std::tuple<const int&>, std::tuple<>}; _Tp = std::_Rb_tree_node<std::pair<const int, Item> >; std::allocator_traits<std::allocator<_CharT> >::allocator_type = std::allocator<std::_Rb_tree_node<std::pair<const int, Item> > >]'      
c:\mingw\lib\gcc\mingw32\6.3.0\include\c++\bits\stl_tree.h:543:32:   required from 'void std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_M_construct_node(std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_Link_type, _Args&& ...) [with _Args = {const std::piecewise_construct_t&, std::tuple<const int&>, std::tuple<>}; _Key = int; _Val = std::pair<const int, Item>; _KeyOfValue = std::_Select1st<std::pair<const int, Item> >; _Compare = std::less<int>; _Alloc = std::allocator<std::pair<const int, Item> >; std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_Link_type = std::_Rb_tree_node<std::pair<const int, Item> >*]'
c:\mingw\lib\gcc\mingw32\6.3.0\include\c++\bits\stl_tree.h:560:4:   required from 'std::_Rb_tree_node<_Val>* std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_M_create_node(_Args&& ...) [with _Args = {const std::piecewise_construct_t&, std::tuple<const int&>, std::tuple<>}; _Key = int; _Val = std::pair<const int, Item>; _KeyOfValue = std::_Select1st<std::pair<const int, Item> >; _Compare = std::less<int>; _Alloc = std::allocator<std::pair<const int, Item> >; std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_Link_type = std::_Rb_tree_node<std::pair<const int, Item> >*]'
c:\mingw\lib\gcc\mingw32\6.3.0\include\c++\bits\stl_tree.h:2196:64:   required from 'std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::iterator std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_M_emplace_hint_unique(std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::const_iterator, _Args&& ...) [with _Args = {const std::piecewise_construct_t&, std::tuple<const int&>, std::tuple<>}; _Key = int; _Val = std::pair<const int, Item>; _KeyOfValue = std::_Select1st<std::pair<const int, Item> >; _Compare = std::less<int>; _Alloc = std::allocator<std::pair<const int, Item> >; std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::iterator = std::_Rb_tree_iterator<std::pair<const int, Item> >; std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::const_iterator = std::_Rb_tree_const_iterator<std::pair<const int, Item> >]'
c:\mingw\lib\gcc\mingw32\6.3.0\include\c++\bits\stl_map.h:483:8:   required from 'std::map<_Key, _Tp, _Compare, _Alloc>::mapped_type& std::map<_Key, _Tp, _Compare, _Alloc>::operator[](const key_type&) [with _Key = int; _Tp = Item; _Compare = std::less<int>; _Alloc = std::allocator<std::pair<const int, Item> >; std::map<_Key, _Tp, _Compare, _Alloc>::mapped_type = Item; std::map<_Key, _Tp, _Compare, _Alloc>::key_type = int]'
c:\Users\user\Desktop\Marcos\signIn-signUp\main.h:68:24:   required from here
c:\mingw\lib\gcc\mingw32\6.3.0\include\c++\tuple:1586:70: error: no matching function for call to 'Item::Item()'
         second(std::forward<_Args2>(std::get<_Indexes2>(__tuple2))...)
                                                                      ^
In file included from c:\Users\user\Desktop\Marcos\signIn-signUp\main.cpp:1:0:
c:\Users\user\Desktop\Marcos\signIn-signUp\main.h:36:5: note: candidate: Item::Item(std::__cxx11::string, std::function<void()>)
     Item(const std::string received_name, std::function<void()> received_function) {
     ^~~~
c:\Users\user\Desktop\Marcos\signIn-signUp\main.h:36:5: note:   candidate expects 2 arguments, 0 provided
c:\Users\user\Desktop\Marcos\signIn-signUp\main.h:32:5: note: candidate: Item::Item(std::__cxx11::string)
     Item(const std::string received_name) {
     ^~~~
c:\Users\user\Desktop\Marcos\signIn-signUp\main.h:32:5: note:   candidate expects 1 argument, 0 provided
c:\Users\user\Desktop\Marcos\signIn-signUp\main.h:26:8: note: candidate: Item::Item(const Item&)
 struct Item {
        ^~~~
c:\Users\user\Desktop\Marcos\signIn-signUp\main.h:26:8: note:   candidate expects 1 argument, 0 provided
c:\Users\user\Desktop\Marcos\signIn-signUp\main.h:26:8: note: candidate: Item::Item(Item&&)
c:\Users\user\Desktop\Marcos\signIn-signUp\main.h:26:8: note:   candidate expects 1 argument, 0 provided
PS C:\Users\user\Desktop\Marcos\signIn-signUp>

2021-08-30 21:35 UTC, nahueespinosa commented
Ok, I see, here is the problem:

```cpp
items_map[call_code].assigned_function();
```

This is what `operator[]` on a `std::map` does from [cpp reference](https://en.cppreference.com/w/cpp/container/map/operator_at):

> Returns a reference to the value that is mapped to a key equivalent to key, performing an insertion if such key does not already exist.

So, it needs to be able to insert an element if it doesn't exist. This element will try to use `Item()` constructor but it doesn't find it, hence the compiler error.

Anyways, you probably don't want to create empty items nor let the map insert them from user calls. That's why you should be using [`at()`](https://en.cppreference.com/w/cpp/container/map/at) which will throw if it doesn't find the key.

Good call asking about this. It's never a good idea to let things like these slide into your code without understanding what's happening.

2021-08-30 21:50 UTC, marcosmarp commented
Got it! Thanks for the explanation!

One thing, in both `CallAssignedFunction` calls, the keys are indeed valid. So why it's the operator trying to create a new element in the map?

2021-08-30 21:54 UTC, nahueespinosa commented
Oh, it's not evaluating if the keys are valid at compilation time. That will happen at runtime.

The compiler is failing because it will need the `Item()` constructor to compile just in case there is a call at runtime that sends an invalid key. It can't know what will happen, but you're telling it: "here there might be an insertion, now compile the code".

2021-08-30 22:35 UTC, marcosmarp commented
That should be it! Let me know if you catch anything else.

2021-08-30 22:55 UTC, nahueespinosa requested changes

2021-08-30 22:55 UTC, nahueespinosa commented on main.h
> +    Item(const std::string received_name, std::function<void()> received_function = NULL) {
Don't use `NULL`, use [nullptr](https://en.cppreference.com/w/cpp/language/nullptr) instead.

http://clchiou.github.io/notes-effective-modern-c++/2017-01-14/item-08-prefer-nullptr-to-0-and-null

2021-08-30 22:55 UTC, nahueespinosa commented on main.h
> +    items_map.emplace(call_code, item_temp);
```suggestion
    items_map.emplace(call_code, Item{name});
```

2021-08-30 22:55 UTC, nahueespinosa commented on main.h
> +    items_map.emplace(call_code, item_temp);
Same here.

2021-08-30 22:55 UTC, nahueespinosa commented on main.h
> +    items_map.at(call_code).assigned_function();
So...

> What happens if there is no function assigned and the user tries to call it?

e.g. the "Exit" item.

2021-08-30 23:02 UTC, nahueespinosa commented on main.h
> +  void CallAssignedFunction(const int& call_code) {
No need to use a ref for an int.

2021-08-30 23:02 UTC, nahueespinosa commented on main.h
> +  void AddItem(const int call_code, const std::string name, std::function<void()> received_function) {
Plenty of need to use a ref for a `std::string`

2021-08-30 23:02 UTC, nahueespinosa commented on main.h
> +  void AddItem(const int call_code, const std::string name) {
Same here

2021-08-30 23:02 UTC, nahueespinosa commented on main.h
> +    Item(const std::string received_name, std::function<void()> received_function = NULL) {
Missing ref as well..

2021-08-30 23:18 UTC, marcosmarp commented on main.h
> +    items_map.at(call_code).assigned_function();
Forgot about that one! Solved it

2021-08-30 23:23 UTC, marcosmarp commented
Sorry for the double commit, forgot to add the rest of the changes in the first one. 
Regarding the invalid key handling, I checked out the [`map::at`](https://www.cplusplus.com/reference/map/map/at/) reference that you gave me and decided to use the built in `throw` of the operator. Let me know if it's a better way to do this

2021-08-30 23:32 UTC, nahueespinosa requested changes
Please, search your code looking for `std::string` passed by value

2021-08-30 23:32 UTC, nahueespinosa commented on main.h
>      Item item_temp(name);
Remove this.

2021-08-30 23:32 UTC, nahueespinosa commented on main.h
> +    }
Oh, you don't need to catch any exception. Exceptions are good. Think about my question and let me know if you don't understand it.

2021-08-30 23:32 UTC, nahueespinosa commented on main.h
> +    }
What happens if you give it a `call_code` for an existing item (like "Exit" in your app) that doesn't have an assigned function?

Map will certainly find the object... So, is not related to `std::out_of_range`.

2021-08-30 23:34 UTC, nahueespinosa commented on main.h
> +    }
You can try it in your code if you want.

```cpp
main_menu.CallAssignedFunction(3);
```

2021-08-31 03:34 UTC, marcosmarp commented on main.h
> +    }
Sorry, I misunderstood the question.

When calling the assigned function of an Item without an assigned function this is the output in console:

```
terminate called after throwing an instance of 'std::bad_function_call'
  what():  bad_function_call
```
Should we leave it that way or should I handle the exception?

2021-09-01 16:30 UTC, nahueespinosa commented on main.h
> +    }
Sorry for the late reply. You shouldn't handle the exception. But it's very important to ask those questions and see if the answer (throwing an exception) is what you need.

If the function had been an good-old function pointer, the program would have crashed. In that case, you would have had to implement the check yourself.

2021-09-01 16:31 UTC, nahueespinosa requested changes

2021-09-01 16:31 UTC, nahueespinosa commented on main.h
>      }
So, remove this and we're done!

2021-09-01 18:59 UTC, merged