Create .gitignore gile
marcosmarp/signIn-signUp pull request #5
Opened 2021-08-07 02:04 UTC by marcosmarp

Closes #3

2021-08-07 02:36 UTC, nahueespinosa requested changes
Cool! One more think you will need to do in this PR is to untrack the files that git is already tracking.
After that git will ignore them with these settings.

https://www.codeblocq.com/2016/01/Untrack-files-already-added-to-git-repository-based-on-gitignore/

2021-08-07 06:22 UTC, marcosmarp commented
\

2021-08-07 17:50 UTC, nahueespinosa requested changes
I think the easiest solution would be to create a new branch and try again honestly.
Take a look at https://github.com/marcosmarp/signIn-signUp/issues/3#issuecomment-894684791

2021-08-07 17:50 UTC, nahueespinosa commented on main.cpp
> +#include "base_functions.h"
The fact that these files show up as changes might indicate something went wrong when running `git init` on an already initialized repo.

2021-08-08 01:47 UTC, closed without merging

2021-08-08 01:47 UTC, marcosmarp commented
Closing cause it was resolved in #8