Delete using namespace std in all the files
marcosmarp/signIn-signUp pull request #7
Opened 2021-08-07 06:54 UTC by marcosmarp

Solves #4

2021-08-07 17:58 UTC, nahueespinosa requested changes
It's difficult to compare the changes, as the repository history is kind of messed up.
I think it looks good in general (left some comments).

Also, please untrack `main.exe`.

Might be a good idea to fix the gitignore branch and then fix this.

2021-08-07 17:58 UTC, nahueespinosa commented on tempCodeRunnerFile.h
> +std::string
Did you mean to add this new file?

2021-08-07 17:58 UTC, nahueespinosa commented on main.cpp
> +		/* If the users enters a std::string of some kind, everything goes crazy, i have to work on that */
Not necessary to edit the comments xD. I'm guessing you used an auto replace feature.

2021-08-07 22:32 UTC, marcosmarp commented on tempCodeRunnerFile.h
> +std::string
I didn't! I think is a header created by Visual Studio (i switched from Dev C++ to Visual Studio recently). Could it be?

Btw: sorry for the delay in responding, i just got home.

2021-08-07 22:32 UTC, marcosmarp commented on main.cpp
> +		/* If the users enters a std::string of some kind, everything goes crazy, i have to work on that */
Lmao I didn't noticed that. Indeed, search and replace

2021-08-07 22:33 UTC, marcosmarp commented
Will solve #3 before this one!

2021-08-08 01:51 UTC, marcosmarp commented
Now that #3 is solved, can I update this branch so is up to date with the main? Is there a way to do that?

2021-08-08 15:01 UTC, nahueespinosa commented
I just rebased the branch with main to make it easier for you. I'll explain how to rebase later!
For now, as your local branch is different from remote (and doesn't share a history anymore), you will need to delete it and fetch the branch again.

```bash
git checkout main
git pull
git branch -D marcos/replace_using_name_space_std        # Delete local branch
git checkout marcos/replace_using_name_space_std         # Fetch and checkout to updated branch
```

Don't forget to address the comments:

- Remove `tempCodeRunnerFile.h`
- Remove `main.exe`
- Fix comment in `main.cpp`

2021-08-08 16:12 UTC, marcosmarp commented
Thanks! A question: when I commit the changes it git bash, I think that every change i made share the summary of what I did. Am I using the wrong command? This is what I use 

>$ git add "changedfile1"
$ git add "changedfile2"
$ git commit -m "summary"

This way, i think both files share the summary when I push them to the origin

2021-08-08 17:23 UTC, nahueespinosa commented
Yeah, a commit usually includes changes to more than one file.
Take a look at [this page](https://www.atlassian.com/git/tutorials/saving-changes) for more information.

> The git add command adds a change in the working directory to the staging area. It tells Git that you want to include updates to a particular file in the next commit. However, git add doesn't really affect the repository in any significant way—changes are not actually recorded until you run git commit.

2021-08-08 17:35 UTC, marcosmarp commented
Just read it! There's one thing I didn't quite understood. 

What if i modify different files for different reasons? How do I comment in each one what i did when commiting and pushing?

For example, what you commented earlier. I didn't addressed each particular change on each file, they all just were pushed with the "deleted using namespace std" summary

2021-08-08 17:43 UTC, nahueespinosa commented
You would do something like:

```bash
# Changes some files
$ git add "changedfile1"
$ git add "changedfile2"
$ git commit -m "changes to implement part of my work"
# Changes other files
$ git add "changedfile2"
$ git add "changedfile3"
$ git commit -m "changes to implement a different part of my work"
# More changes
$ git add "changedfile1"
$ git commit -m "last small fix to the previous commited code"
```

Then you'll end up with a history of 3 commits reflecting your work in your feature branch. Of course "Squash and merge" will still squash them all in one single commit representing the whole feature.

2021-08-08 17:54 UTC, marcosmarp commented
Got it! Thanks.

Just deleted the local branch and fetched again. .exe seems to be running just fine, and the .gitignore is there. Should I do anything else before merging?

2021-08-08 18:08 UTC, nahueespinosa commented
Yes!

- Remove `tempCodeRunnerFile.h`
- Remove `main.exe`
- Fix comment in `main.cpp`

Commit those changes and push them.

2021-08-08 18:16 UTC, marcosmarp commented
Just done it! Sorry, forgot about doing those 3 changes.

2021-08-08 18:33 UTC, nahueespinosa approved these changes
Approved! Great

2021-08-08 18:40 UTC, merged