Create gitignore (sec try)
marcosmarp/signIn-signUp pull request #8
Opened 2021-08-07 22:56 UTC by marcosmarp

Solves #3

2021-08-07 22:58 UTC, marcosmarp commented
I think that now is working. I can't see the undesired files in the new branch.

2021-08-07 23:58 UTC, nahueespinosa requested changes
Great news!

Mmh, I don't think `LogInDataBase.dev` is the file you want to exclude as it seems to contain some type of configuration for your project.

I mentioned `LogInDataBase` (without the extension) as that file seems to be the final executable (correct me if I'm wrong). So to remove it you would need to directly write its name in `.gitignore`.

2021-08-07 23:58 UTC, nahueespinosa commented on .gitignore
> +*.exe
```suggestion
*.exe
LogInDataBase
```

That would be my suggestion.

2021-08-08 00:32 UTC, marcosmarp commented on .gitignore
> +*.exe
I just checked and I'm pretty sure that the LogInDataBase and the .dev file were generated by Dev C++. 
The IDE already generated a .exe but i never upload it, I thought (wrongly) that you only uploaded the .exe in the releases, but as I can see now you have to add it to the code too.

The reason why I'm saying those two files are generated by Dev C++ is cause I created a new project in another IDE, copied the .cpp and .o files of this project and compiled and those files weren't generated

2021-08-08 01:14 UTC, nahueespinosa commented on .gitignore
> +*.exe
Got it, then let's remove all Dev C ++ files from this repository as they depend on the IDE.
The `.exe` would be part of a release. You don't have to add it to the repo, that's why we want git to ignore that file.

2021-08-08 01:27 UTC, nahueespinosa approved these changes
Looking good! Let's merge this 🎉

2021-08-08 01:30 UTC, marcosmarp commented
Hey, didn't saw your approval and added the IDE files extensions to the .gitignore file. Is that okay?

2021-08-08 01:36 UTC, nahueespinosa commented on .gitignore
> +* LogInDataBase
```suggestion
# Dev C++ IDE     #
###################
```
I'd change this. Remove `* LogInDataBase` and separate the following lines specifying the reason why they are being ignored.

I think you can accept the suggestion directly from GitHub and that will create a commit.

2021-08-08 01:46 UTC, merged

2021-08-08 01:46 UTC, marcosmarp commented
Ready to go! Merging the PR!